### ISSUE TITLE
Is it possible to create a strict context with this library?

### ISSUE THREAD

**Issue by ekaradon** [dai-shi/use-context-selector#103]
Hello,

As always, every time I'm thinking about a state something library, there is a Dai-Shi one! I love it. Thanks for your hard work on all those!

So, until recently, when I wanted to ascertain that some data was available and not having to manage any `Maybe` type, I put the data into a strict context which allowed me to remove any kind of uncertainty on the data, but also to fail fast when the developer was trying to use the context outside of the provider.
See an example here:

```ts
/*
 * This function allows us to define a context with the following advantages:
 * - No need to check whether or not the context data is initialized (no undefined allowed)
 * - Remove direct access to the Context, only the provider and the hook are provided
 * See references:
 *  - https://juliangaramendy.dev/blog/strict-react-context
 *  - https://dev.to/juliang/why-i-never-use-react-usecontext-4ddf (fallback)
 *  - https://kentcdodds.com/blog/how-to-use-react-context-effectively
 * Example: const [ThingProvider, useThing] = createStrictContext<Thing>({ name: 'Thing' })
 */

import { createContext, useContext } from 'react'
import type { Maybe } from './types'

type CreateStrictContextOptions = {
  errorMessage?: string
  name: string
}

export function createStrictContext<T>(options: CreateStrictContextOptions) {
  const Context = createContext<Maybe<T>>(undefined)

  Context.displayName = options.name

  function useStrictContext(): NonNullable<T> {
    const context = useContext(Context)
    if (!context) {
      throw new Error(
        `[${options.name}] ${
          options.errorMessage ?? 'Context Provider is missing.'
        }`,
      )
    }
    return context
  }

  return [Context.Provider, useStrictContext] as const
}
```

However, more and more, I feel like it would be nice (but not mandatory to be clear), to be able to select the data I want to pick. In order to prevent any wasteful re-render for all my components. 

But, because I want to use a selector in order to prevent re-render, it also means that I don't have an easy way to know whether or not the context has been defined (eg: the hook has been called within a provider). Is there a way for me to do this?

**Comment by dai-shi** [comment]
Maybe use `useContext` to check if it's defined then use `useContextSelector`?
I think you can throw an error in the selector too.

**Comment by ekaradon** [comment]
I may be missing something, but if I call `useContext`, I suppose that it will trigger a re-render everytime the context changes, even if the selected value doesn't change?

**Comment by dai-shi** [comment]
gotcha. you are absolutely right. my bad.

**Comment by dai-shi** [comment]
Maybe you need a nested context.

**Comment by ekaradon** [comment]
Not sure to follow If I'm being honest. Nested context like when you override an existing one? Do you have some references or examples to point me?

**Comment by dai-shi** [comment]
No, there are no examples, AFAIR.
Nested context means a context whose value is another context.
The first one can be with React.createContext, the second one will be with `use-context-selector`.
Anyway, it would not be what you want.

> I think you can throw an error in the selector too.

How about this one ☝️ ?

**Comment by ekaradon** [comment]
Oh indeed, sounds like a perfect plan. Something like this I suppose then? 

```ts

import { createContext, useContextSelector } from 'use-context-selector'
import type { Maybe } from './types'
import { isDefined } from './value'

type CreateStrictContextOptions = {
  errorMessage?: string
  name: string
}

export function createStrictContext<T>({
  name,
  errorMessage,
}: CreateStrictContextOptions) {
  const Context = createContext<Maybe<T>>(undefined)

  Context.displayName = name

  function useContext<Selected>(selector: (state: T) => Selected): Selected {
    return useContextSelector(Context, (state) => {
      if (!isDefined(state)) {
        throw new Error(
          `[${name}] ${errorMessage ?? 'Context Provider is missing.'}`,
        )
      }
      return selector(state)
    })
  }

  return [Context.Provider, useContext] as const
}
```

I don't see why it would not work perfectly as expected. Thanks again dai-shi!

**Comment by dai-shi** [comment]
👏
