### ISSUE TITLE
[question] Why is the scheduler dependency required?

### ISSUE THREAD

**Issue by romgrk** [dai-shi/use-context-selector#106]
I was wondering if there was a way to remove it from the peer dependencies. Thanks.

**Comment by dai-shi** [comment]
Because it is used in the code:
https://github.com/dai-shi/use-context-selector/blob/bd4eb7492f0c2cfe9a1050ce924cf46c2f1b1150/src/index.ts#L19

You might be interested in reading the discussion in #100.

**Comment by romgrk** [comment]
I've read the code, but I don't understand why wrapping the listener callbacks with `runWithNormalPriority` is required. If you could point me to resources to understand the issue better I'd be super happy to understand more about this.

**Comment by dai-shi** [comment]
If you need to dive into it, you want to follow resources linked in https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-rendering.
Some links might be outdated.

In reality, if you don't care much about the subtle behavior, you could implement much simpler version of `useContextSelector`.

**Comment by romgrk** [comment]
> you could implement much simpler version

Yeah I figured, I have a very minimal implementation here: https://gist.github.com/romgrk/a3dc5d3de5c011e0925b2f2aee14ee98 (if you have any comments, I'd be interested to hear)


> if you don't care much about the subtle behavior

Actually I do care about correctness, if you have any comments to make on the issues that could arise from not having the scheduler wrapper I'd be happy to hear. Otherwise, feel free to close this issue, and thanks for the replies.

**Comment by dai-shi** [comment]
One small note is that `useEffect` can technically be fired with a big delay, so the store state can be changed before you subscribe to the store.

Other than that, it should be "level 1". 
It will probably fail with level 2 and 3.
To be level 2, you can just use `useSyncExternalStore`.
To be level 3, it's basically impossible, and my hack is to use `scheduler` and some others.

See https://github.com/reactwg/react-18/discussions/70 for levels.
