### ISSUE TITLE
Can you review my hook? (useKeyedContextSelector)

### ISSUE THREAD

**Issue by casamia918** [dai-shi/use-context-selector#108]
https://github.com/casamia918/example-dropdown-select-use-context-selector

Hi. I've just pushed above repo. 

I like this library. But as the "useContextSelector" hook need some setup parameters, I've wrote a simple "useKeyedContextSelector" hook, which the return value is type safed by the given keys.

I want to be reviewed by original hook author. Thanks.

**Comment by dai-shi** [comment]
I didn't look at the code but isn't it close to https://github.com/dai-shi/react-hooks-global-state ?

**Comment by casamia918** [comment]
Nope. It is just a wrapper of "useContextSelector". But it simplifies the usage code.

Um... Maybe, this is not a big deal. I close this issue by myself. Sorry.
