### ISSUE TITLE
how to stop re-rendering with React.memo?

### ISSUE THREAD

**Issue by mgenev** [dai-shi/use-context-selector#11]
Hi,
React.memo has a comparator parameter which can stop a component from re-rendering, but it automatically receives only the props.

If we have context with context selector which creates a binding to that property, how can we use React.memo or something else to prevent a re-render?

I have a situation in which I have a parent with a grid, and it needs to track where the focus is on the children.  So I need the index in the parent, but I don't want the change of index to cause a re-render. If save the focus index in the context and bind that field in the parent, it causes all the children to re-render which makes the performance very bad...

**Comment by dai-shi** [comment]
Here's codesandbox that I created base on your explanation.
https://codesandbox.io/s/wild-paper-ktdyw

It works as expected for me. Note: `areEqual` return always `true`.
Does it help for your case?

**Comment by mgenev** [comment]
Thank you that works!
