### ISSUE TITLE
Version 1.4.2 specifies main module field that cannot be resolved

### ISSUE THREAD

**Issue by disrae** [dai-shi/use-context-selector#115]
# Summary
- Version 1.4.1 is working, but 1.4.2 gives the following error. 
- I am on react 18.2
![image](https://github.com/dai-shi/use-context-selector/assets/26100016/49396fcd-76ce-4ecb-9b08-7c634ed0eea3)

**Comment by ProjectProgramAMark** [comment]
getting this error too

**Comment by dai-shi** [comment]
Thanks for reporting!
That's my oversight. Let me fix it soon.

**Comment by dai-shi** [comment]
It's a little bit new situation.
#116 would be one attempt. If it works, it's good to go. I wonder if the metro bundler support export conditions.
Could anyone please try it?
https://ci.codesandbox.io/status/dai-shi/use-context-selector/pr/116
☝️ Find "Local Install Instructions"

**Comment by disrae** [comment]
That appears to work, the error goes away, the app loads as expected. 
I didn't test the functionality of use-context-selector, but I assume it is unaffected.

**Comment by dai-shi** [comment]
Sounds great! Let's ship it.

**Comment by disrae** [comment]
Do I need to close the issue?

**Comment by rtturner** [comment]
@dai-shi confirmed this fixes issue I was experiencing as well. From our `use-context-select` perspective: all tests pass, CI builds app for both iOS / Android, and app functions correctly. Thanks for the fix

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-context-selector/v/1.4.3

**Comment by antFrancon** [comment]
@dai-shi From the [Metro documentation](https://metrobundler.dev/docs/package-exports/#recommended-introducing-exports-is-a-breaking-change), introducing exports should be considered a breaking change for the library.

In my case, I am unable to run your solution because enabling { resolver: { unstable_enablePackageExports: true } } in metro.config.js breaks many other package imports.

**Comment by dai-shi** [comment]
That was my concern. So, metro doesn't support exports by default yet. 🤔 
I wonder if you guys are on the same RN version.

**Comment by dai-shi** [comment]
Does this fix?
https://ci.codesandbox.io/status/dai-shi/use-context-selector/pr/118

**Comment by dai-shi** [comment]
> you can include both "react-native" and "exports" > "react-native"

Ah, nice if that works.

**Comment by dai-shi** [comment]
See #118 updated

**Comment by antFrancon** [comment]
It's all good

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-context-selector/v/1.4.4
