### ISSUE TITLE
useMemo vs useContextSelector

### ISSUE THREAD

**Issue by Miteshdv** [dai-shi/use-context-selector#117]
Hi, 
May you please let me know , why to prefer this library over useMemo?

**Comment by dai-shi** [comment]
As of now, you can't stop triggering rerenders when context updates, even with useMemo.

See some old discussions:
- https://github.com/facebook/react/issues/14110
- https://blog.axlight.com/posts/4-options-to-prevent-extra-rerenders-with-react-context/
