### ISSUE TITLE
Issue is back, missing some kind of export for react native.

### ISSUE THREAD

**Issue by disrae** [dai-shi/use-context-selector#119]
Works with fix from 1.4.3, but broken again on 1.4.4

![image](https://github.com/dai-shi/use-context-selector/assets/26100016/a4862354-c96d-4f04-92ef-c84c41d97c70)

**Comment by dai-shi** [comment]
@antFrancon Do you have any idea?

**Comment by disrae** [comment]
Ah, pardon.
expo: no
react-native: 0.68.7
metro: 0.67.0

metro.config
```
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```

**Comment by disrae** [comment]
Is it just me? I'll give it another whirl, see if maybe I did something wrong.

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/use-context-selector/v/2.0.0-beta.0 is published. Please give a try. If there's a problem, please open a new issue.
