### ISSUE TITLE
I have a question about state rendering time

### ISSUE THREAD

**Issue by lovetingyuan** [dai-shi/use-context-selector#129]
https://github.com/dai-shi/use-context-selector/assets/7310471/089bb191-3616-4e6e-ad4c-342dcf1a01f5

I use `use-context-selector` and `zustand` to write the same app, to add the pets count.

component of "Dogs" will cost 100ms to render, I click the "dog up" button 5 times in one second very quickly.

The UI rendering result seems different, `use-context-selector` shows number 5(the final result) directly(I know it is not rendered directly, just looks like that.), but `zustand` show number from 0 to 5(this is better for user experince).

I know it is related to react reconciliation progress. I know you are the author of both libs, Could you explain the detail about this problem? Thanks very much!

**Comment by dai-shi** [comment]
As you don't share the code, it's only my guess.
use-context-selector does something really tricky to simulate context behavior as much as possible. It's not meant for performance.
zustand, on the other hand, simply uses `useSyncExternalStore`.

However, 100ms sounds too long.
You might want to try a different version of useContextSelector with useSyncExternalStore, shown here: https://github.com/dai-shi/use-context-selector/issues/109#issuecomment-1785147682

**Comment by lovetingyuan** [comment]
> As you don't share the code, it's only my guess. use-context-selector does something really tricky to simulate context behavior as much as possible. It's not meant for performance. zustand, on the other hand, simply uses `useSyncExternalStore`.
> 
> However, 100ms sounds too long. You might want to try a different version of useContextSelector with useSyncExternalStore, shown here: [#109 (comment)](https://github.com/dai-shi/use-context-selector/issues/109#issuecomment-1785147682)

I use the useSyncExternalStore version you mentioned in the comment, and the render result is same as zustand version.
Thank you
