### ISSUE TITLE
How to use dynamic selection of data based on the passed arguments?

### ISSUE THREAD

**Issue by vorillaz** [dai-shi/use-context-selector#131]
Hey there, thanks for the great package. I've tried to dig through the issues, but I couldn't find any answer to my problem.
My state has a quite deep and structure:
```js
const state = {
    user: {
        name: "Bob",
        surname: "Doe",
        age: 21
    }
}
```

Obviously I could create an isolated selector for each field and retrieve each part of the user properly thus avoiding re-renders. But I am looking for a more abstract approach to retrieve slices of the state without causing re-renders in the component level.

I've tried to use something like:
```js
const getUserField = (stateKey) => {
  return useContextSelector(Context, ({ state }) => {
    return state["user"][stateKey];
  });
};

const UserField = ({ stateKey }) => {
  const value = getUserField(stateKey);
  return (
    <>
      <span>{stateKey}</span>
      <span>{value}</span>
    </>
  );
};

const User = () => {
  const fields = ["name", "surname", "age"];
  return (
    <div>
      {fields.map((field) => (
        <UserField key={field} stateKey={field} />
      ))}
    </div>
  );
};
```
But I can see that every time some part of the user's state is update is causing a rendering  all sub-components. 
Any help will be highly appreciated.

**Comment by dai-shi** [comment]
> ```js
> const getUserField = (stateKey) => {
>   return useContextSelector(Context, ({ state }) => {
>     return state["user"][stateKey];
>   });
> };
> ```

This looks good as is.
Can you create a minimal reproduction with https://stackblitz.com ?

**Comment by vorillaz** [comment]
Sure @dai-shi,
https://stackblitz.com/edit/vitejs-vite-wrfq4u

It appears that each component retrieving their slice of the state gets rendered twice.

**Comment by dai-shi** [comment]
https://stackblitz.com/edit/vitejs-vite-ypqmm7?file=src%2Fctx.tsx

You should make `dispatch` function stable and also select it.

**Comment by dai-shi** [comment]
I don't think it's related with OP's question. Closing this.
