### ISSUE TITLE
All child components are re-rendering. Is this the intended behavior?

### ISSUE THREAD

**Issue by livemehere** [dai-shi/use-context-selector#142]
```tsx
import { createContext, useContextSelector } from "use-context-selector";
import { useState } from "react";

const context = createContext(null);

const Counter1 = () => {
  const count1 = useContextSelector(context, (v) => v[0].count1);
  const setState = useContextSelector(context, (v) => v[1]);
  const increment = () =>
    setState((s) => ({
      ...s,
      count1: s.count1 + 1,
    }));
  console.log("count1 render"); // here
  return (
    <div>
      <span>Count1: {count1}</span>
      <button type="button" onClick={increment}>
        +1
      </button>
      {Math.random()}
    </div>
  );
};

const Counter2 = () => {
  const count2 = useContextSelector(context, (v) => v[0].count2);
  const setState = useContextSelector(context, (v) => v[1]);
  const increment = () =>
    setState((s) => ({
      ...s,
      count2: s.count2 + 1,
    }));
  console.log("count2 render"); // here
  return (
    <div>
      <span>Count2: {count2}</span>
      <button type="button" onClick={increment}>
        +1
      </button>
      {Math.random()}
    </div>
  );
};

const StateProvider = ({ children }) => (
  <context.Provider value={useState({ count1: 0, count2: 0 })}>{children}</context.Provider>
);

const App = () => (
  <StateProvider>
    <Counter1 />
    <Counter2 />
  </StateProvider>
);

export default App;

```

Since the value injected into Provider via value is a ref, I understood that the parent Provider component itself, acting as the parent in this example, does not re-render. Therefore, I assumed that child components would not re-render due to the parent’s re-rendering.

In that case, when I add console.log statements to each component in the example provided, I expect each component to re-render only in response to changes in the values selected by each useContextSelector. However, this is not the case.

Even when calling the following:
```tsx
 const increment = () =>
    setState((s) => ({
      ...s,
      count1: s.count1 + 1,
    }));
```

the <Counter2 /> component is triggered, and console.log('counter2 render') is printed.

I’d like to ask if this is the intended behavior or a bug.

**Comment by livemehere** [comment]
```tsx
import { createContext, useContextSelector } from "@fluentui/react-context-selector";
```

With this change, I observed that it behaves as expected.

**Comment by dai-shi** [comment]
It's intentional to support subtle behavior. You can use `useEffect` to console.log just once.
If you don't need the subtlety (which is 99% case actually), you can use the simpler version.

https://github.com/dai-shi/use-context-selector/issues/109#issuecomment-1785147682

**Comment by dai-shi** [comment]
See also #107.

**Comment by livemehere** [comment]
thanks !

**Comment by ugurakin1** [comment]
Sorry but I'm a little bit confused, what's the point of the selector pattern if subscribers of any value in the context will re-render on any context value changing? I might be missing or confusing something but I thought this was the entire point of the pattern?

**Comment by dai-shi** [comment]
It rerenders, but no commits happen. This is the technique used in this library. People wouldn't need this capability. Check out #149 too.
