### ISSUE TITLE
Warnings in test 

### ISSUE THREAD

**Issue by Shadowlauch** [dai-shi/use-context-selector#15]
Sorry for posting another issue. I just updated to the new React version and the new context-selector version and I'm getting a lot of warnings in my test suit. 

Can I do anything to avoid this flood of warnings?

**Comment by dai-shi** [comment]
There's [a long story](https://github.com/dai-shi/use-context-selector/issues/7) behind it, but yeah flooding of the warning is not nice for your app test.
I'll make a fix later.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-context-selector/v/1.1.1

@Shadowlauch Thanks for reporting this!
