### ISSUE TITLE
React Layout Effect will throw an error on server render

### ISSUE THREAD

**Issue by ooade** [dai-shi/use-context-selector#18]
It's in the React doc (https://reactjs.org/docs/hooks-reference.html#uselayouteffect). We can make use of the layout effect hook if it's on the client then on the server, we use the effect hook.

I can send in a PR.

**Comment by lishine** [comment]
He has some useImorphicLayoutEffect in react-async-reducer or in react-tracked

**Comment by ooade** [comment]
That will work 👍

**Comment by dai-shi** [comment]
Yeah, I'm using it in v2 too. #12 

For v1, we may actually need to run it in render.
Do you have a specific use case you are working on?

**Comment by ooade** [comment]
> Yeah, I'm using it in v2 too. #12
> 
> For v1, we may actually need to run it in render.
> Do you have a specific use case you are working on?

Haha, not at the moment. Seen the v2. It looks good!

**Comment by ooade** [comment]
Closing this as it will be resolved in v2.
