### ISSUE TITLE
useIsoLayoutEffect

### ISSUE THREAD

**Issue by LXSMNSYC** [dai-shi/use-context-selector#24]
Currently, `useIsoLayoutEffect` is synchronously called in SSR mode, in contrast with how side-effects should never run on SSR mode, infinite re-renders may occur in this case, specially below https://github.com/dai-shi/use-context-selector/blob/d22abe3e101e719762b5d2248b38a7316de7f3e7/src/index.js#L40-L48

I think this is an ideal implementation: https://github.com/reduxjs/react-redux/blob/master/src/utils/useIsomorphicLayoutEffect.js

**Comment by dai-shi** [comment]
Okay, this was intentional and worked pre-v1.2. But, as v1.2 introduced `setVersion`, it gets crazy... Thanks for the notice.
