### ISSUE TITLE
Possible to miss update?

### ISSUE THREAD

**Issue by csr632** [dai-shi/use-context-selector#29]
If an update happens before [useIsomorphicLayoutEffect](https://github.com/dai-shi/use-context-selector/blob/d1e16845f13cc4f72afc27ac47029c8a1b978bcb/src/index.ts#L174) is triggered, where listener is added, the `dispatch` of consumer will not be called(because listener has not been added yet). And it will stay at the old state forever.

**Comment by dai-shi** [comment]
As far as I understand, child effects fire before parent effect, so should be fine?
Is it theoretical, or can you create a repro? I might be misunderstanding something.

**Comment by csr632** [comment]
Yes I just realize you only emit events in Provider's `useLayoutEffect`. So consumers won't miss any events.
