### ISSUE TITLE
Tearing!

### ISSUE THREAD

**Issue by csr632** [dai-shi/use-context-selector#31]
https://codesandbox.io/s/use-context-selector-tears-hx1qx

This test is actually failing: https://github.com/dai-shi/use-context-selector/blob/aa5c2d7fe33343c38073969227825f1cb119ccbe/__tests__/02_tearing_spec.tsx#L45
But the test didn't catch the error.

**Comment by dai-shi** [comment]
Yes, that was the whole point of having used `changedBits=0`.
Since v1.3, it won't work. v2-alpha won't work too. It's something we can't solve in userland as far as I understand currently.
The spec is kept in the repo (as well as 03_stale_props) to show the limitation. Those two specs are skipped.

**Comment by csr632** [comment]
Oh I guess I didn't fully understand this line in README :)
> Tearing is only avoided within the Provider tree. A value outside the Provider will tear. (02_tearing_spec fails)

**Comment by dai-shi** [comment]
@csr632 Would you have any suggestion to improve the line in README? I'm not confident it's well written.

**Comment by csr632** [comment]
How about https://github.com/dai-shi/use-context-selector/pull/32

**Comment by dai-shi** [comment]
Yeah, that explains more carefully. Thanks for the suggestion. Closing this.
