### ISSUE TITLE
Preact: scheduler

### ISSUE THREAD

**Issue by mischnic** [dai-shi/use-context-selector#35]
I'm trying to use jotai with Preact with 
```
  "alias": {
    "react": "preact/compat",
    "react-dom": "preact/compat",
    "scheduler": false
  }
```
but this of course fails with `t.unstable_runWithPriority is not a function` because `scheduler` is needed...

Is there a way to make it work?

**Comment by dai-shi** [comment]
Ohhhh, I actually expected this lib doesn't work with preact, but that means jotai doesn't work either.

One way would be to develop compat version of scheduler in preact, which would help not only this lib but other libs.

The other way is to make this lib fallback when it doesn't have the function. Let me quickly try this.
