### ISSUE TITLE
Can we destructuring useContextSelector?

### ISSUE THREAD

**Issue by rimsila** [dai-shi/use-context-selector#42]
I avoid it will not optimize performance or re-render. So, Can I  destructuring useContextSelector or not. thanks you

`const { loadingLogOut, loadingUserProfile } = useContextSelector(ctxAuth, (v) => v[0]);`

**Comment by dai-shi** [comment]
If I understand your question correctly:
- destructuring doesn't help optimizing re-renders with useContextSelector.
- what you are looking for is [react-tracked](https://github.com/dai-shi/react-tracked), which is based on use-context-selector.

Closing this, but feel free to add more comments.

**Comment by rimsila** [comment]
> If I understand your question correctly:
> 
> * destructuring doesn't help optimizing re-renders with useContextSelector.
> * what you are looking for is [react-tracked](https://github.com/dai-shi/react-tracked), which is based on use-context-selector.
> 
> Closing this, but feel free to add more comments.

Thanks you for your answer and the answer is  destructuring doesn't help optimizing re-renders right?

**Comment by dai-shi** [comment]
Yes, and that what react-tracked is for. I call it render optimization with state usage tracking.
Ref: https://blog.axlight.com/posts/what-is-state-usage-tracking-a-novel-approach-to-intuitive-and-performant-api-with-react-hooks-and-proxy/

Historically, I developed react-tracked at first, and later extracted non-tracking part to create `use-context-selector`.
