### ISSUE TITLE
Jest cannot find module react-dom

### ISSUE THREAD

**Issue by gsevla** [dai-shi/use-context-selector#52]
![image](https://user-images.githubusercontent.com/36795971/128927023-77928c58-38f8-4f61-9e52-bbf04b81670b.png)

If more info needed, let me know.

I'm using react native 0.63.3 and use-context-selector ^1.3.7.

**edit**
I guess it's happening because use-context-selector is trying to import from index.umd.js instead index.native.umd.js.

I'm wondering if it's really caused by use-context-selector or jest. But how can I fix it? Anyone already passthrough it?

**Comment by dai-shi** [comment]
Thanks for reporting.
If umd.js is an issue, can you try the resolver?
https://jestjs.io/docs/configuration#resolver-string
> By combining defaultResolver and packageFilter we can implement a package.json "pre-processor" that allows us to change how the default resolver will resolve modules. For example, imagine we want to use the field "module" if it is present, otherwise fallback to "main":


...but, that's just a workaround. I wonder how we could solve this without such a workaround. help wanted. (this issue is probably not only with use-context-selector but with all my other packages with microbundle.)

**Comment by gsevla** [comment]
It worked!

Thanks for the answer.

I readed about the problem, but have no ideas to solve it, sorry (have no expertise with bundlers)

**Comment by dai-shi** [comment]
Good to hear that.

No problem. Let's leave this issue open for a while in case someone jumps in.

**Comment by BrunoADPaixao** [comment]
> Thanks for reporting. If umd.js is an issue, can you try the resolver? https://jestjs.io/docs/configuration#resolver-string
> 
> > By combining defaultResolver and packageFilter we can implement a package.json "pre-processor" that allows us to change how the default resolver will resolve modules. For example, imagine we want to use the field "module" if it is present, otherwise fallback to "main":
> 
> ...but, that's just a workaround. I wonder how we could solve this without such a workaround. help wanted. (this issue is probably not only with use-context-selector but with all my other packages with microbundle.)

I'm having the same error. Using this solution now a have the same error but with the index.modern.js. Any sugestion?

**Comment by dai-shi** [comment]
So, is this the problem with RN + jest? It works with RN only and maybe React (web) + jest, does it?

**Comment by mtroskot** [comment]
@gsevla can you post the workaround steps how to fix the issue?
