### ISSUE TITLE
two questions regarding the useContextUpdate hook

### ISSUE THREAD

**Issue by snsie** [dai-shi/use-context-selector#56]
Q1:

If the initial README example is updated to rely on concurrent mode, should the Counter1 component be modified as shown below?

from:
```
const Counter1 = () => {
  const count1 = useContextSelector(context, v => v[0].count1);
  const setState = useContextSelector(context, v => v[1]);
  const increment = () => setState(s => ({
    ...s,
    count1: s.count1 + 1,
  }));
  return (
    <div>
      <span>Count1: {count1}</span>
      <button type="button" onClick={increment}>+1</button>
      {Math.random()}
    </div>
  );
};
```
 to:
```
const Counter1 = () => {
  const count1 = useContextSelector(context, v => v[0].count1);
  const setState = useContextSelector(context, v => v[1]);
  const update = useContextUpdate();
  const increment = update(() => setState(s => ({
    ...s,
    count1: s.count1 + 1,
  })));
  return (
    <div>
      <span>Count1: {count1}</span>
      <button type="button" onClick={increment}>+1</button>
      {Math.random()}
    </div>
  );
};
```

Q2:

I'm trying to improve the performance of an app that uses this library to update multiple contexts. Some contexts only consist of a couple variables, but a couple of the contexts save state as lists with thousands of entries that are updated at 60fps (ideally). Should I only wrap the heavier state updates with the ```update``` const or all of the state updates indiscriminately?

**Comment by dai-shi** [comment]
Q1: Yes. Note React 18 Alpha doesn't have Concurrent Mode any more, and if you want to enable Concurrent Rendering, you would need to update in `startTransition`.

Q2: What `update` does is only trigger rendering in callback to show "pending" state with `useTransition`. Time slicing should work without using `useContextUpdate`. So, unless you have any visible issues, `useContextUpdate` isn't necessary. That's something not clearly described in README. `update` can be slow in your use case, as it's more or less a hack to mimic the `useState` behavior.

**Comment by snsie** [comment]
Thank you for the advice!

**Comment by dai-shi** [comment]
You are welcome, and thanks for asking.
