### ISSUE TITLE
Stale props issue

### ISSUE THREAD

**Issue by liviudobrea** [dai-shi/use-context-selector#58]
Hei brother,
Thanks for this awesome lib !

When you have the time, could you please look over this piece of code and confirm that this is the _correct_ way of reproducing the stale props late revalidation issue ?
https://codesandbox.io/s/usecontextselector-late-state-update-lopcv

I've been having some troubles with late updates in my app and only found out about this after carefully debugging parts of my app that contained memoized data parts provided by `use-context-selector`.
In case that's true, for use cases where instant re-validation is needed, would you recommend simply using react's context instead and **NOT** `use-context-selector` ?

Thanks !

**Comment by dai-shi** [comment]
If I understand your example correctly, it is not the stale prop issue that's defined/originated from react-redux.
What you observe is tearing with react state value and use-context-selector value. It used to work in the previous versions, but from v1.3, it's the known limitation.
I would suggest to use https://github.com/dai-shi/use-context-selector#usecontext, and not use React.useContext at all.

**Comment by liviudobrea** [comment]
Thanks for clarifying and for the recommendation !
