### ISSUE TITLE
Using use-context-selector in _app.tsx return undefined (Next.js)

### ISSUE THREAD

**Issue by VitorGouveia** [dai-shi/use-context-selector#59]
So, I have been building an app with next.js and just ran into a minor problem

when calling either useContext or useContextSelector in _app.tsx the return is always undefined

```
"next": "latest"
"react": "^17.0.2",
"use-context-selector": "^1.3.9",
"scheduler": "^0.20.2",
```

is this expected behaviour?

**Comment by dai-shi** [comment]
No... Is it nextjs specific? Can you make sure you have a Provider up in the tree?
You might want to provide a minimal reproduction.
