### ISSUE TITLE
Trigger the rendering of the component twice in a certain scenario

### ISSUE THREAD

**Issue by y805939188** [dai-shi/use-context-selector#61]
DAISHI さん、こんにちは.
僕はプロジェクトで”use-context-selector”を使いましたが、下のような demo で、子のコンポーネントが二回をトリガーされました．

demo：https://codesandbox.io/s/billowing-breeze-em4lk?file=/src/App.tsx
再現方法：1. コンソールを開く、2. <input/>に文字を入力します
現象：Child のコンポーネントが二回をトリガーされました

上記の demo では、react によって提供される "context" を使うと、子のコンポーネントは1回だけトリガーされました．
僕は react の更新がバッチ処理されない原因となるコードがあるかどうかを推測しています.
ありがとう.

**Comment by dai-shi** [comment]
Thanks for a lovely description.
This is an expected behavior. It's a limitation and how our userland solution works.
If you remove useState, it doesn't double render.
https://codesandbox.io/s/ecstatic-hofstadter-x2t22

**Comment by y805939188** [comment]
> Thanks for a lovely description. This is an expected behavior. It's a limitation and how our userland solution works. If you remove useState, it doesn't double render. https://codesandbox.io/s/ecstatic-hofstadter-x2t22

ok~thank you 👍
