### ISSUE TITLE
Shallow check in object/array destructuring.

### ISSUE THREAD

**Issue by heyitsarpit** [dai-shi/use-context-selector#70]
Zustand has the [`shallow`](https://github.com/pmndrs/zustand#selecting-multiple-state-slices) as the second argument to optimize for referential equality.

Is it possible to do something like that with this library?

```ts
  const sdkReader = useSDK((s) => s.sdkReader)
  const sdkWriter = useSDK((s) => s.sdkWriter)
```

Can we write this in one line with destructuring ?

**Comment by dai-shi** [comment]
I found this very controversial, but at this point, I wouldn't do it probably unless React does it.
See #19 for long discussions.
