### ISSUE TITLE
`createContext` return type is `any`

### ISSUE THREAD

**Issue by heyitsarpit** [dai-shi/use-context-selector#71]
So this doesn't seem to be an issue with the library(maybe), but the returned type for `createContext` is `any` when I hover over it VSCode, but if I try writing something with it, the autocomplete correctly completes the fields.

Looking at the type definition in the `node_modules`, and it looks correct to me.

<img width="538" alt="Screenshot 2022-03-04 at 9 17 27 PM" src="https://user-images.githubusercontent.com/18533307/156796068-c4797edd-c0b0-474a-8a1b-a086008fe8bb.png">

<img width="615" alt="Screenshot 2022-03-04 at 9 17 47 PM" src="https://user-images.githubusercontent.com/18533307/156795099-1c3f3493-f24b-4646-9118-2e818e0e9eeb.png">

The weirdest thing is if I hover over `Context.Provider`, it shows the correct type.

**Comment by dai-shi** [comment]
Interesting...

I wonder if this `as any` does anything wired.
https://github.com/dai-shi/use-context-selector/blob/9e5174ea4ca2725c9177e5c672e1dcd880186ede/src/index.ts#L110

Happy to see anyone has any suggestions.

**Comment by VitorGouveia** [comment]
@heyitsarpit are you using typescript or just the vscode intellisense?
just to be sure

**Comment by heyitsarpit** [comment]
> @heyitsarpit are you using typescript or just the vscode intellisense?
> just to be sure

The codebase is typescript, the screenshot I posted are vscode's on hover type inspection.

**Comment by heyitsarpit** [comment]
@orta The issue is a year old and I just checked and don't observer this behaviour anymore. Things working as expected. I guess we can close the issue.
