### ISSUE TITLE
`setState` on `useSubscription` apollo update

### ISSUE THREAD

**Issue by sidnetopia** [dai-shi/use-context-selector#72]
Is there any chance to update the state when updates from apollo subscription comes in?

In my `App.js`, whenever the received `status` is `accepted`, it should update two values in the `state`. One is an update on the value of array of objects (`state.object[idx].status = accepted`) and the other is setting a new value (`state.object2 = queried data`) from `query`.

**Comment by dai-shi** [comment]
The usage of use-context-selector is the same as normal React Context.
setState and useSubscription have nothing to do with React Context.
While not ideal, syncing useState and apollo subscription can be done with `useEffect`.
```js
  const [state, setState] = useState();
  const { data } = useSubscription(...);
  useEffect(() => {
    setState(data);
  }, [data]);
```
Hope it helps.

**Comment by sidnetopia** [comment]
> The usage of use-context-selector is the same as normal React Context.
> setState and useSubscription have nothing to do with React Context.
> While not ideal, syncing useState and apollo subscription can be done with useEffect.
> 
>   const [state, setState] = useState();
>   const { data } = useSubscription(...);
>   useEffect(() => {
>     setState(data);
>   }, [data]);
> Hope it helps.

This solved my issue. Thank you!
