### ISSUE TITLE
Why using runWithNormalPriority in createProvider?

### ISSUE THREAD

**Issue by djknight1** [dai-shi/use-context-selector#74]
While reading source code, it's hard to understand why you using `runWithNormalPriority` in `createProvider`.
Would you mind explaining it?

**Comment by dai-shi** [comment]
We want to use useLayoutEffect, because useEffect is not appropriate (too late to change state).
React seems to use high priority in useLayoutEffect, so we need to force changing to normal priority. otherwise, rendering can't be interrupted.

**Comment by djknight1** [comment]
@dai-shi 
Thanks for responding
