### ISSUE TITLE
How does selector memoization work?

### ISSUE THREAD

**Issue by RunDevelopment** [dai-shi/use-context-selector#81]
The RFC proposes that _both_ [the context and the selector are memoized](https://github.com/gnoff/rfcs/blob/context-selectors/text/0000-context-selectors.md#implement-usecontextselector-hook-reactfiberhooks). 

However, it seems like this library works differently. E.g.:

```js
  const count1 = useContextSelector(context, v => v[0].count1);
```

From my understanding of the RFC, this should defeat the memorization and make `useContextSelector` ineffective as a performance optimization.

Obviously, the above snippet works for this library, so could you please explain how? Is the selector memoized, and if so, how?

To cite a more complex example, let's look at this snippet:

```js
function Foo({ id }) {
  const value: number = useContextSelector(Context, c => c.values[id])
  return <>{id} = {value}</>
}
```

How will this behave if both `Context` and `id` may change? (If props are too constant, then `id` may also be state.)

**Comment by dai-shi** [comment]
As far as I understand, the RFC says if the selector is memoized like
```js
  const count1 = useContextSelector(context, useCallback(v => v[0].count1, []));
```
It skips re-evaluation. But, if not
```js
  const count1 = useContextSelector(context, v => v[0].count1);
```
It will re-evaluate.

So, it's just about optimization of re-evaluation of the selector function.

This library doesn't include such optimization, assuming the selector function is fairly lightweight.

> How will this behave if both `Context` and `id` may change?

It will use the latest values, so it behaves correctly.

Is it clear? I'm afraid I don't get the point of your question.

**Comment by RunDevelopment** [comment]
Thank you for your explanation.

In that case, I think there is a bug in the `useContextSelector` implementation of this library. [This dependency array](https://github.com/dai-shi/use-context-selector/blob/4982b426f90cc0fc2ca0880d800f79189247a522/src/index.ts#L202) should also include `selector`.

Right now, the `selector` captured by the reducer function can become stale. This happens with the following steps:

1. Let the context be the number 1, and the selector be `() => 1`.
2. Change the selector to be `c => c` (yield the whole context).
    This will cause the `selector` in `useReducer` to be become stale because the deps array is still `[value, selected] = [1, 1]`
3. Change the context to 2. 
    The stale `selector` will still return 1. 

I think those steps will produce incorrect results.

**Comment by dai-shi** [comment]
Sorry for code readability, but that's not a dependency array. It's an initial value for `useReducer`. `selector` will never be stale.

**Comment by RunDevelopment** [comment]
I see. Thank you for the clarification.
