### ISSUE TITLE
user-context-selector is not supported  React Native 0.68 ?

### ISSUE THREAD

**Issue by dev01-linvix** [dai-shi/use-context-selector#84]
user-context-selector is not supported  React Native 0.68 ?

**Comment by dai-shi** [comment]
Looking at #82, it seems like people are using it with RN 0.68, maybe?

**Comment by Rodrigojorge** [comment]
It worked for me on RN, thank you by the way.

But I'm trying to run some tests with Jest on RN now and I received an error requiring `react-dom`. I can try to manage that but I wonder if it should be required by this lib...

` Cannot find module 'react-dom' from 'node_modules/use-context-selector/dist/index.umd.js'`

**Comment by Rodrigojorge** [comment]
```
const ReactDom = {
  render: jest.fn(),
}

export default ReactDom;

```
