### ISSUE TITLE
Plans to support react 18

### ISSUE THREAD

**Issue by kfiku** [dai-shi/use-context-selector#86]
Hello, do you have plans to support react 18?

its working crazy with react 18 - example here https://codesandbox.io/s/context-selector-forked-st5bps

**Comment by dai-shi** [comment]
It supports React 18.

The behavioral change is expected and it's not an issue. It's what I call extra-render-with-no-commits behavior.
FYI: https://twitter.com/dai_shi/status/1534170089981100032

**Comment by kfiku** [comment]
thanks for your help :)
