### ISSUE TITLE
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jemliF** [dai-shi/use-context-selector#90]
Environment:

Next.js: 12.1.6
use-context-selector: 1.4.1
scheduler: 0.23.0

**Comment by dai-shi** [comment]
Hmmmm, I'm not sure what's happening. There are memory leaks somewhere, right?

**Comment by jemliF** [comment]
Yes, following the complete stack trace:
> Ready on http://localhost:3000
wait  - compiling /[lang]/[[...slug]] (client and server)...
wait  - compiling...
event - compiled client and server successfully in 4.5s (1552 modules)
Using contentful environment: 'develop' through proxy

<--- Last few GCs --->

[11632:000001F58AA15320]   408575 ms: Mark-sweep (reduce) 8186.8 (8205.0) -> 8186.5 (8205.8) MB, 6746.2 / 0.0 ms  (average mu = 0.592, current mu = 0.000) allocation failure scavenge might not succeed
[11632:000001F58AA15320]   421587 ms: Mark-sweep (reduce) 8187.5 (8202.8) -> 8187.1 (8203.8) MB, 13011.1 / 0.0 ms  (average mu = 0.334, current mu = 0.000) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 00007FF7267F481F napi_wrap+110783
 2: 00007FF726797F26 v8::base::CPU::has_sse+61862
 3: 00007FF726798E26 node::OnFatalError+294
 4: 00007FF7270723BE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF72705718D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF726F002CC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF726EEAD5B v8::internal::NativeContextInferrer::Infer+59739
 8: 00007FF726ED003F v8::internal::MarkingWorklists::SwitchToContextSlow+56959
 9: 00007FF726EE3D1B v8::internal::NativeContextInferrer::Infer+31003
10: 00007FF726EDADFD v8::internal::MarkCompactCollector::EnsureSweepingCompleted+6285
11: 00007FF726EE2F6E v8::internal::NativeContextInferrer::Infer+27502
12: 00007FF726EE6FBB v8::internal::NativeContextInferrer::Infer+43963
13: 00007FF726EF09B2 v8::internal::ItemParallelJob::Task::RunInternal+18
14: 00007FF726EF0941 v8::internal::ItemParallelJob::Run+641
15: 00007FF726EC3FC3 v8::internal::MarkingWorklists::SwitchToContextSlow+7683
16: 00007FF726EDB2AC v8::internal::MarkCompactCollector::EnsureSweepingCompleted+7484
17: 00007FF726ED9AE4 v8::internal::MarkCompactCollector::EnsureSweepingCompleted+1396
18: 00007FF726ED7668 v8::internal::MarkingWorklists::SwitchToContextSlow+87208
19: 00007FF726F060B1 v8::internal::Heap::LeftTrimFixedArray+929
20: 00007FF726F081A5 v8::internal::Heap::PageFlagsAreConsistent+789
21: 00007FF726EFD3D1 v8::internal::Heap::CollectGarbage+2049
22: 00007FF726EFB5D5 v8::internal::Heap::AllocateExternalBackingStore+1349
23: 00007FF726F1BA3B v8::internal::Factory::NewFillerObject+203
24: 00007FF726C4A0B1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
25: 00007FF7270FB27D v8::internal::SetupIsolateDelegate::SetupHeap+465325
26: 0000025E4D9BA6CA
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jemliF** [comment]
Sometimes, I have the Following:

> Ready on http://localhost:3000
wait  - compiling /[lang]/[[...slug]] (client and server)...
wait  - compiling...
event - compiled client and server successfully in 10.9s (1552 modules)
Using contentful environment: 'develop' through proxy

<--- Last few GCs --->

[20472:000001B2C0B1E110]   106788 ms: Mark-sweep (reduce) 4092.9 (4102.8) -> 4092.6 (4103.8) MB, 6354.8 / 0.0 ms  (average mu = 0.062, current mu = 0.000) allocation failure scavenge might not succeed
[20472:000001B2C0B1E110]   112198 ms: Mark-sweep (reduce) 4093.6 (4105.8) -> 4093.3 (4106.3) MB, 5408.7 / 0.0 ms  (average mu = 0.031, current mu = 0.000) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7267F481F napi_wrap+110783
 2: 00007FF726797F26 v8::base::CPU::has_sse+61862
 3: 00007FF726798E26 node::OnFatalError+294
 4: 00007FF7270723BE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF72705718D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF726F002CC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF726F0B6EA v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
 8: 00007FF726F08829 v8::internal::Heap::PageFlagsAreConsistent+2457
 9: 00007FF726EFD3D1 v8::internal::Heap::CollectGarbage+2049
10: 00007FF726EFB5D5 v8::internal::Heap::AllocateExternalBackingStore+1349
11: 00007FF726F1BA3B v8::internal::Factory::NewFillerObject+203
12: 00007FF726C4A0B1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
13: 00007FF7270FB27D v8::internal::SetupIsolateDelegate::SetupHeap+465325
14: 00007FF72713600A v8::internal::SetupIsolateDelegate::SetupHeap+706362
15: 000002CD7CBAB3E7
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dai-shi** [comment]
Can you try removing the library and see if the problem persist?

**Comment by jemliF** [comment]
This is how my context look like:

import React, { ReactNode, useReducer } from 'react';
import { createContext } from 'use-context-selector';
import { IItemHeaderNiv2 } from '../@types/generated/contentful';

type State = {
 prop1: type;
prop2: type;
};

type Action =
  | {
      type: 'SET_PROP1';
      payload: type;
    }
  | {
      type: 'SET_PROP2';
      payload: type;
    };

type Dispatch = (action: Action) => void;

const initialState = {
  prop1: value,
prop2: value
};

const reducer = (state: State, action: Action) => {
  switch (action.type) {
    case 'SET_PROP1':
      return { ...state, prop1: action.payload };
    case 'SET_PROP2':
      return { ...state, prop2: action.payload };
    default:
      throw new Error(`Unknown action: ${JSON.stringify(action)}`);
  }
};

export const useValue = () => useReducer(reducer, initialState);

export const MainContext = createContext<[State, Dispatch]>([initialState, () => null]);
export const MainProvider = ({ children }: { children: ReactNode }) => (
  <MainContext.Provider value={useValue()}>{children}</MainContext.Provider>
);

**Comment by dai-shi** [comment]
Thanks for confirming.
This library itself doesn't keep anything in memory, so there's anything we can do unless someone finds some exact bugs.
I would try updating React, updating Node.js (Next.js?), and maybe configuring memory options in Node.js.

**Comment by dai-shi** [comment]
I think it's unrelated. closing.
