### ISSUE TITLE
Context.Provider as HOC with memoized children - children still rerender on any state change

### ISSUE THREAD

**Issue by lightrow** [dai-shi/use-context-selector#92]
here is my setup:

```jsx
const Screen = withVideoPlayer(() => {
      const load = useContextSelector(VideoPlayerContext, c => c.load);

      console.log("Screen rerendered")
  ...
})
```
```jsx
const withVideoPlayer = <P extends object>(WrappedComponent: FC<P>) => {
    const ComponentWithPlayerContext = (props: P) => {
        const controller = useInitVideoPlayerController();

        const Memoized = useMemo(() => memo(WrappedComponent), [WrappedComponent]);

        return (
            <VideoPlayerContext.Provider value={controller}>
                <Memoized {...props} />
            </VideoPlayerContext.Provider>
        );
    };

    return ComponentWithPlayerContext;
};
```

```js
const useInitVideoPlayerController = () => {

  const load = useCallback(
        async (
            video: IVideo | IVideoTrailer,
            options?: Partial<{
                autoplay: boolean;
                position: number;
            }>,
        ) => {
            dispatch({ type: 'load', payload: { video, options } });
        },
        [],
  );

  ...

  return {
      ... a bunch of state properties and methods wrapped with useCallback
      load,
  };
}
```
the problem is the Screen component rerenders any time the context is changed, even though it only uses "load" method which is wrapped with useCallback without dependencies. If i remove `const load = useVideoPlayer(c=>c.load)` from Screen, the rerenders don't happen anymore.

could this be related to this? https://github.com/dai-shi/use-context-selector/issues/86

**Comment by jmikrut** [comment]
I'm also seeing this, and I read #86. We're trying to adopt this package for [Payload CMS](https://payloadcms.com) and I have a few questions that I would love to discuss.

So, I noticed this, like OP, when I added a `console.log` in some components to test when they rerender. They all go crazy rerendering. BUT if I wrap the `console.log` in a `useEffect`, then the console.log stops.

However, with React DevTools, I turned on "Highlight updates when components render" and all of my components are still flashing, matching when the `console.log` was in the body of the component.

@dai-shi I know you've mentioned elsewhere that this is expected, but doesn't this come with some type of performance impact?

**Comment by dai-shi** [comment]
Yes, this is an expected behavior.
React render has two phases, 1) render phase for invoking render function and b) commit phase to apply changes to DOM.
What you see with console.log in the render function is 1) and what you see in useEffect is 2).
It impacts on performance if your render function is computationally heavy. In such cases, you want to use `useMemo` and/or `React.memo` to avoid extra computations.

**Comment by lightrow** [comment]
well, this stings a bit, but if nothing can be done about it, so be it

**Comment by jmikrut** [comment]
Beautiful. I actually think this is not too bad. @dai-shi you are a boss. Payload has an open PR using your package and we’re gonna merge it soon. 👍

**Comment by lightrow** [comment]
so i assume if we used React's own Context, it would always go to phase 2?
